// ── Decade example songs ───────────────────────────────────────
export const DECADE_SONGS = {
  '80s': [
    'Billie Jean - Michael Jackson',
    'Beat It - Michael Jackson',
    'Thriller - Michael Jackson',
    'Like a Virgin - Madonna',
    'Material Girl - Madonna',
    "Sweet Child O' Mine - Guns N' Roses",
    "Don't Stop Believin' - Journey",
    'Girls Just Want to Have Fun - Cyndi Lauper',
    'True Colors - Cyndi Lauper',
    'Take On Me - a-ha',
    'Every Breath You Take - The Police',
    'Roxanne - The Police',
    'Africa - Toto',
    "Livin' on a Prayer - Bon Jovi",
    'You Give Love a Bad Name - Bon Jovi',
    'Come On Eileen - Dexys Midnight Runners',
    'Wake Me Up Before You Go-Go - Wham!',
    'Careless Whisper - George Michael',
    'Faith - George Michael',
    'Total Eclipse of the Heart - Bonnie Tyler',
    "Don't You (Forget About Me) - Simple Minds",
    'Everybody Wants to Rule the World - Tears for Fears',
    'Shout - Tears for Fears',
    'Eye of the Tiger - Survivor',
    'Footloose - Kenny Loggins',
    'I Wanna Dance with Somebody - Whitney Houston',
    'Greatest Love of All - Whitney Houston',
    'Pour Some Sugar on Me - Def Leppard',
    'With or Without You - U2',
    'Where the Streets Have No Name - U2',
    '99 Luftballons - Nena',
    'Never Gonna Give You Up - Rick Astley',
    'Jump - Van Halen',
    'Call Me - Blondie',
    'Tainted Love - Soft Cell',
    'Video Killed the Radio Star - The Buggles',
    'Blue Monday - New Order',
    'Love Shack - B-52s',
    'Should I Stay or Should I Go - The Clash',
    'Push It - Salt-N-Pepa',
    'Walking on Sunshine - Katrina and the Waves',
    'Take My Breath Away - Berlin',
    'Dancing in the Dark - Bruce Springsteen',
    'Under Pressure - Queen & David Bowie',
    "Don't Stop Me Now - Queen",
    'The Final Countdown - Europe',
    'Here I Go Again - Whitesnake',
    'I Just Called to Say I Love You - Stevie Wonder',
    "What's Love Got to Do with It - Tina Turner",
    'Hungry Like the Wolf - Duran Duran',
  ].join('\n'),

  '90s': [
    'Smells Like Teen Spirit - Nirvana',
    'Come as You Are - Nirvana',
    'Baby Got Back - Sir Mix-a-Lot',
    'Waterfalls - TLC',
    'No Scrubs - TLC',
    "Gangsta's Paradise - Coolio",
    'Wannabe - Spice Girls',
    'Spice Up Your Life - Spice Girls',
    '...Baby One More Time - Britney Spears',
    'I Will Always Love You - Whitney Houston',
    'My Heart Will Go On - Celine Dion',
    'Creep - Radiohead',
    'Killing Me Softly - Fugees',
    'Ready or Not - Fugees',
    'One - U2',
    'Under the Bridge - Red Hot Chili Peppers',
    'Black Hole Sun - Soundgarden',
    'Zombie - The Cranberries',
    'Dreams - The Cranberries',
    'Vogue - Madonna',
    'Nothing Compares 2 U - Sinéad O\'Connor',
    'November Rain - Guns N\' Roses',
    'Iris - Goo Goo Dolls',
    'Smooth - Santana ft. Rob Thomas',
    'Mambo No. 5 - Lou Bega',
    'Livin\' La Vida Loca - Ricky Martin',
    'Believe - Cher',
    'The Sign - Ace of Base',
    'Wonderwall - Oasis',
    "Don't Look Back in Anger - Oasis",
    'Bitter Sweet Symphony - The Verve',
    'Common People - Pulp',
    'What Is Love - Haddaway',
    'Good Riddance (Time of Your Life) - Green Day',
    'Basket Case - Green Day',
    'Semi-Charmed Life - Third Eye Blind',
    'Jump Around - House of Pain',
    'Ice Ice Baby - Vanilla Ice',
    "U Can't Touch This - MC Hammer",
    'Return of the Mack - Mark Morrison',
    'Losing My Religion - R.E.M.',
    'I Want It That Way - Backstreet Boys',
    "Everybody (Backstreet's Back) - Backstreet Boys",
    "Tearin' Up My Heart - NSYNC",
    "I'll Be There for You - The Rembrandts",
    'Lovefool - The Cardigans',
    'Stay - Lisa Loeb',
    "Breakfast at Tiffany's - Deep Blue Something",
    'Two Princes - Spin Doctors',
    'Mr. Jones - Counting Crows',
  ].join('\n'),

  '2000s': [
    'Crazy in Love - Beyoncé',
    'Yeah! - Usher',
    'In da Club - 50 Cent',
    'Umbrella - Rihanna',
    'Crazy - Gnarls Barkley',
    'SexyBack - Justin Timberlake',
    'Single Ladies (Put a Ring on It) - Beyoncé',
    'Rehab - Amy Winehouse',
    'Hey Ya! - OutKast',
    'Beautiful Day - U2',
    'Boulevard of Broken Dreams - Green Day',
    'Mr. Brightside - The Killers',
    'Take Me Out - Franz Ferdinand',
    'Seven Nation Army - The White Stripes',
    'Lose Yourself - Eminem',
    'Numb - Linkin Park',
    'In the End - Linkin Park',
    'Complicated - Avril Lavigne',
    'Sk8er Boi - Avril Lavigne',
    'Hot in Herre - Nelly',
    'Gold Digger - Kanye West',
    'Hips Don\'t Lie - Shakira',
    'Hollaback Girl - Gwen Stefani',
    'Ms. Jackson - OutKast',
    'Poker Face - Lady Gaga',
    'Just Dance - Lady Gaga',
    'Low - Flo Rida',
    'Apologize - Timbaland ft. OneRepublic',
    'Unwritten - Natasha Bedingfield',
    'Since U Been Gone - Kelly Clarkson',
    "Stacy's Mom - Fountains of Wayne",
    'Feel Good Inc. - Gorillaz',
    'Clocks - Coldplay',
    'Fix You - Coldplay',
    'Chasing Cars - Snow Patrol',
    'Say My Name - Destiny\'s Child',
    'Toxic - Britney Spears',
    'Beautiful - Christina Aguilera',
    'SOS - Rihanna',
    'Irreplaceable - Beyoncé',
    'Bootylicious - Destiny\'s Child',
    'Buttons - The Pussycat Dolls',
    "Don't Cha - The Pussycat Dolls",
    'Beautiful Girls - Sean Kingston',
    'White Flag - Dido',
    'Hanging by a Moment - Lifehouse',
    'The Scientist - Coldplay',
    'Fighter - Christina Aguilera',
    'With You - Chris Brown',
    'Float On - Modest Mouse',
  ].join('\n'),

  '2010s': [
    'Rolling in the Deep - Adele',
    'Someone Like You - Adele',
    'Hello - Adele',
    'Happy - Pharrell Williams',
    'Blurred Lines - Robin Thicke',
    'Get Lucky - Daft Punk',
    'Call Me Maybe - Carly Rae Jepsen',
    'Gangnam Style - PSY',
    'Uptown Funk - Mark Ronson ft. Bruno Mars',
    'Shape of You - Ed Sheeran',
    'Thinking Out Loud - Ed Sheeran',
    'Photograph - Ed Sheeran',
    'Stay With Me - Sam Smith',
    'Take Me to Church - Hozier',
    'Royals - Lorde',
    'Thrift Shop - Macklemore & Ryan Lewis',
    'Shake It Off - Taylor Swift',
    'Blank Space - Taylor Swift',
    'Chandelier - Sia',
    'Cheap Thrills - Sia',
    'We Found Love - Rihanna',
    'Work - Rihanna',
    "Can't Feel My Face - The Weeknd",
    'The Hills - The Weeknd',
    'Hotline Bling - Drake',
    "God's Plan - Drake",
    'Sorry - Justin Bieber',
    'Love Yourself - Justin Bieber',
    'Treat You Better - Shawn Mendes',
    'Old Town Road - Lil Nas X',
    'Bad Guy - Billie Eilish',
    'Havana - Camila Cabello',
    'Despacito - Luis Fonsi ft. Daddy Yankee',
    'Lean On - Major Lazer & DJ Snake',
    'Closer - The Chainsmokers',
    'Stressed Out - Twenty One Pilots',
    'Somebody That I Used to Know - Gotye',
    'We Are Young - fun.',
    'Pumped Up Kicks - Foster the People',
    'Radioactive - Imagine Dragons',
    'Counting Stars - OneRepublic',
    'Let Her Go - Passenger',
    'Moves Like Jagger - Maroon 5',
    'Wake Me Up - Avicii',
    'Titanium - David Guetta ft. Sia',
    'Rather Be - Clean Bandit',
    "Can't Stop the Feeling - Justin Timberlake",
    'Demons - Imagine Dragons',
    'Best Song Ever - One Direction',
    'Cheerleader - OMI',
  ].join('\n'),

  '2020s': [
    'Blinding Lights - The Weeknd',
    'Levitating - Dua Lipa',
    "Don't Start Now - Dua Lipa",
    'drivers license - Olivia Rodrigo',
    'good 4 u - Olivia Rodrigo',
    'brutal - Olivia Rodrigo',
    'vampire - Olivia Rodrigo',
    'obsessed - Olivia Rodrigo',
    'MONTERO (Call Me by Your Name) - Lil Nas X',
    'Industry Baby - Lil Nas X ft. Jack Harlow',
    'Easy On Me - Adele',
    'As It Was - Harry Styles',
    'Watermelon Sugar - Harry Styles',
    'Anti-Hero - Taylor Swift',
    'Cruel Summer - Taylor Swift',
    'Flowers - Miley Cyrus',
    'Unholy - Sam Smith & Kim Petras',
    'About Damn Time - Lizzo',
    'Running Up That Hill - Kate Bush',
    'Heat Waves - Glass Animals',
    'Stay - The Kid LAROI & Justin Bieber',
    'Leave the Door Open - Silk Sonic',
    'Save Your Tears - The Weeknd',
    'Die For You - The Weeknd',
    'Happier Than Ever - Billie Eilish',
    'Bad Habits - Ed Sheeran',
    'Shivers - Ed Sheeran',
    'Butter - BTS',
    'Dynamite - BTS',
    'Cold Heart - Elton John & Dua Lipa',
    'Kiss Me More - Doja Cat ft. SZA',
    'Calm Down - Rema & Selena Gomez',
    'Escapism - RAYE',
    'Ella Baila Sola - Eslabon Armado ft. Peso Pluma',
    'BZRP Music Sessions Vol. 53 - Bizarrap ft. Shakira',
    'La Bachata - Manuel Turizo',
    'Tití Me Preguntó - Bad Bunny',
    'Me Porto Bonito - Bad Bunny ft. Chencho Corleone',
    'Espresso - Sabrina Carpenter',
    'Please Please Please - Sabrina Carpenter',
    'Feather - Sabrina Carpenter',
    'Beautiful Things - Benson Boone',
    'Lose Control - Teddy Swims',
    'Mood - 24kGoldn ft. iann dior',
    'Peaches - Justin Bieber ft. Daniel Caesar & Giveon',
    'Heartbreak Anniversary - Giveon',
    'Golden Hour - JVKE',
    'APT. - ROSE ft. Bruno Mars',
    'Not Like Us - Kendrick Lamar',
    'Luther - Kendrick Lamar ft. SZA',
  ].join('\n'),

  // ── Spanish / Latin lists ──────────────────────────────────────
  '90s-es': [
    'Macarena - Los del Río',
    'La Flaca - Jarabe de Palo',
    'Ciega, Sordomuda - Shakira',
    'Azúcar Amargo - Fey',
    'La Calle de las Sirenas - OV7',
    'Provócame - Chayanne',
    'María - Ricky Martin',
    'Entre Dos Tierras - Héroes del Silencio',
    'Sin Documentos - Los Rodríguez',
    'Sopa de Caracol - Banda Blanca',
    'De Música Ligera - Soda Stereo',
    'Oye mi Amor - Maná',
    'Livin la Vida Loca - Ricky Martin',
    'El Venao - Los Cantantes',
    'La ventanita - Garibaldi',
    'Suave - Luis Miguel',
    'Muchacha Triste - Los Fantasmas del Caribe',
    'Auto Rojo - Vilma Palma e Vampiros'
  ].join('\n'),

  '2000s-es': [
    'Aserejé - Las Ketchup',
    'Gasolina - Daddy Yankee',
    'La Camisa Negra - Juanes',
    'Atrévete-te-te - Calle 13',
    'Las de la Intuición - Shakira',
    'Me Gustas Tú - Manu Chao',
    'Pobre Diabla - Don Omar',
    'Ni Tú Ni Nadie - Moenia',
    'Y Yo Sigo Aquí - Paulina Rubio',
    'El Run Run - Estopa',
    'Labios Compartidos - Maná',
    'Rakata - Wisin & Yandel',
    'Dime Que No - Ricardo Arjona',
    'Ave María - David Bisbal',
    'Torero - Chayanne',
    'She Bangs - Ricky Martin',
    'No Me Doy Por Vencido (Versión Dance) - Luis Fonsi',
    'Rosa Pastel - Belanova',
    'Don - Miranda!',
    'En el 2000 - Natalia Lafourcade',
    'Limón y Sal - Julieta Venegas',
    'Amante Bandido (Versión Papitour) - Miguel Bosé',
    'Vivir Mi Vida - Marc Anthony',
    'Eres - Café Tacvba',
    'Lento - Julieta Venegas',
    'Sabor a Chocolate - Elefante',
    'Caraluna - Bacilos',
    'Obsesión - Aventura',
    'Siente El Boom - Tito El Bambino',
    'Apretaito - Ozuna',
    'Marta, Sebas, Guille y los demás - Amaral',
    'Princesas - Pereza',
    'Zapatillas - El Canto del Loco',
    'Niña - La Quinta Estación',
    'Geometría Polisentimental - Fangoria',
    'Papola de la Suave - El Arrebato',
    'Yo Quiero Bailar - Sonia y Selena',
    'A Dios Le Pido - Juanes',
    'Color Esperanza - Diego Torres',
    'Que la Detengan - David Civera',
    'Antes Muerta Que Sencilla - María Isabel',
    'Culpable o No - Kalimba',
    'Nada Fue Un Error - Coti',
    'Labios de Fresa - Coque Malla',
    'No Te Pido Flores - Fanny Lu',
    'Malo - Bebe',
    'Camina y Ven - David Bustamante',
    'Baila Casanova - Paulina Rubio',
    'Mayonesa - Chocolate',
    'Tenía tanto que darte - Nena Daconte',
  ].join('\n'),

  '2010s-es': [
    'Danza Kuduro - Don Omar',
    'Ai Se Eu Te Pego - Michel Teló',
    'Bailando - Enrique Iglesias',
    'Despacito - Luis Fonsi',
    'Limbo - Daddy Yankee',
    'Mi Gente - J Balvin',
    'Vivir Mi Vida - Marc Anthony',
    'La Bicicleta - Carlos Vives',
    'Propuesta Indecente - Romeo Santos',
    'El Perdón - Nicky Jam',
    'Sofía - Alvaro Soler',
    'Picky - Joey Montana',
    'On the Floor (Spanish Version) - Jennifer Lopez',
    'Waka Waka (Esto es África) - Shakira',
    'Mayores - Becky G',
    'Échame La Culpa - Demi Lovato',
    'Robarte un Beso - Sebastian Yatra',
    'Baila Baila Baila - Ozuna',
    'La Gozadera - Gente de Zona',
    'Felices los 4 - Maluma',
    'Mía - Bad Bunny',
    'Súbeme la Radio - Enrique Iglesias',
    'El Mismo Sol - Alvaro Soler',
    'Rayos de Sol - Jose de Rico',
    'Te Pintaron Pajaritos - Yandar & Yostin',
    'Darte un Beso - Prince Royce',
    'Pegate - Grupo Treo',
    'Follow the Leader - Wisin & Yandel',
    'Taboo - Don Omar',
    'Adrenalina - Wisin',
    'La Romana - Bad Bunny',
    'Tacones Rojos - Sebastian Yatra',
    'Indecente - Anitta',
    'Vaina Loca - Ozuna',
    'Ella No Sigue Modas - Juan Magán',
    'Danza Kuduro - Lucenzo',
    'Bara Bará Bere Berê - Alex Ferrari',
    'La Mordidita - Ricky Martin',
    'Me Enamoré - Shakira',
    'Bailando por ahí - Juan Magán',
    'Colgando en tus manos - Carlos Baute'
  ].join('\n'),
};
